# Generated by Django 3.2 on 2022-03-11 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220311_1538'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='joinrequest',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='group',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='owned_group', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('user', 'group')},
        ),
    ]
