# Generated by Django 3.2 on 2022-03-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220311_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionrequest',
            options={'ordering': ('-sent',)},
        ),
        migrations.AlterUniqueTogether(
            name='connectionrequest',
            unique_together={('from_group', 'to_group')},
        ),
    ]
